version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  pets:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pets
    depends_on:
      - postgres
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx
    container_name: pets_nginx
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - pets
    ports:
      - "80:80"

volumes:
  static_volume:
  media_volume:
  postgres_data: