# Generated by Django 5.0 on 2023-12-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts', '0002_pts_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pts',
            name='slug',
            field=models.SlugField(max_length=225, unique=True),
        ),
    ]
