# Generated by Django 5.0 on 2023-12-20 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts', '0003_alter_pts_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=225)),
                ('slug', models.SlugField(max_length=225, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pts',
            options={'ordering': ['-publish_date']},
        ),
        migrations.AlterField(
            model_name='pts',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'NotPublished'), (1, 'Published')], default=1),
        ),
        migrations.AddField(
            model_name='pts',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pts.category'),
        ),
        migrations.AddIndex(
            model_name='pts',
            index=models.Index(fields=['-publish_date'], name='pts_pts_publish_6b5c9c_idx'),
        ),
    ]
