# Generated by Django 5.0 on 2023-12-20 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts', '0004_category_alter_pts_options_alter_pts_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pts',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pts.category'),
        ),
    ]
