# Generated by Django 5.0 on 2023-12-21 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts', '0006_tagpost_pts_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pts',
            name='passport',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pass_id', to='pts.passport'),
        ),
    ]
